[project]
name = "chunklet"
version = "1.3.1"
description = "A smart multilingual text chunker for LLMs, RAG, and beyond."
authors = [
  { name = "speedyk_005", email = "speedy40115719@gmail.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Information Technology",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Text Processing",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

keywords = [
  "nlp", "chunking", "text-splitting", "llm", "rag", "ai", "multilingual"
]

dependencies = [
  "pysbd>=0.3.0",
  "sentence-splitter>=1.4",
  "py3langid>=0.3.0",
  "loguru>=0.7.2",
  "pydantic>=2.0",
  "mpire>=0.3.0",
  "rich>=13.0.0",
  "regex>=2023.0.0",
]

[project.urls]
Homepage = "https://github.com/speedyk-005/chunklet"
Repository = "https://github.com/speedyk-005/chunklet"
Documentation = "https://github.com/speedyk-005/chunklet/blob/main/README.md"
Issues = "https://github.com/speedyk-005/chunklet/issues"
Changelog = "https://github.com/speedyk-005/chunklet/blob/main/CHANGELOG.md"

[project.scripts]
chunklet = "chunklet.cli:main"

[project.optional-dependencies]
dev = [
  "pytest>=7.0",
  "pytest-cov",
  "pytest-mock",
  "black",
]

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["chunklet", "chunklet.utils"]

[tool.pytest.ini_options]
minversion = "7.4"
addopts = "--cov=chunklet --cov-report=term-missing:skip-covered --strict-markers --durations=0"
testpaths = ["tests"]
python_files = "test_*.py"

[tool.coverage.report]
omit = [
    "src/chunklet/cli.py"
]

[tool.black]
line-length = 88