[project]
name = "chunklet-py"
version = "2.0.0"
description = "A smart multilingual text chunker for LLMs, RAG, and beyond."
authors = [
  { name = "speedyk_005", email = "speedy40115719@gmail.com" }
]

license = "MIT"
readme = "README.md"
requires-python = ">=3.9"

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Information Technology",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Text Processing",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

keywords = [
  "nlp", "chunking", "text-splitting", "llm", "rag", "ai", "multilingual",
  "text processing", "natural language processing", "data processing",
  "information retrieval", "semantic search", "document processing"
]

dependencies = [
  "pysbd>=0.3.4",
  "sentsplit>=1.0.7",
  "sentencex>=0.6.0",
  "indic-nlp-library>=0.90",
  "py3langid>=0.3.0",
  "pydantic>=2.0.0",
  "mpire>=2.10.0",
  "rich>=13.0.0",
  "more-itertools>=10.8.0",
  "python-box>=7.3.0",
  "regex>=2024.11.6",
  "cachetools>=5.5.2"
]

[project.urls]
Homepage = "https://github.com/speedyk-005/chunklet-py"
Repository = "https://github.com/speedyk-005/chunklet-py"
Documentation = "https://github.com/speedyk-005/chunklet-py/blob/main/README.md"
Issues = "https://github.com/speedyk-005/chunklet-py/issues"
Changelog = "https://github.com/speedyk-005/chunklet-py/blob/main/CHANGELOG.md"

[project.scripts]
chunklet = "chunklet.cli:main"

[project.optional-dependencies]
dev = [
  "pytest>=8.3.5",
  "pytest-cov>=6.2.1",
  "pytest-mock>=3.14.1",
  "black>=25.1.0",
  "flake8>=7.3.0",
  "flake8-pyproject>=1.2.3",
]
document = [
  "pypdf>=5.0.8",
  "pydocx>=0.9.0",
  "docutils>=0.21.2",
  "markdownify>=1.1.0",
  "striprtf>=0.0.29",
  "beautifulsoup4>=4.13.4",
]

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["chunklet", "chunklet.utils", "chunklet.libs", "chunklet.static"]

[tool.pytest.ini_options]
minversion = "7.4"
addopts = "--cov=chunklet --cov-report=term-missing:skip-covered --strict-markers --durations=0"
testpaths = ["tests"]
python_files = "test_*.py"

[tool.coverage.report]
omit = [
    "src/chunklet/cli.py"
]

[tool.black]
line-length = 88

[tool.flake8]
per-file-ignores = [
    "__init__.py:F401",
    "tests/*.py:E501",
]
extend-ignore = ["E501"]
count = true